# Generated by Django 5.1.7 on 2025-04-22 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessage',
            name='nonce_b64',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
