# Generated by Django 5.1.7 on 2025-04-20 06:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appointment_type', models.CharField(choices=[('VIDEO', 'Video Consultation'), ('CLINIC', 'Clinic Visit'), ('HOME', 'Home Visit')], default='VIDEO', max_length=10)),
                ('requested_date', models.DateField()),
                ('requested_time', models.TimeField()),
                ('symptoms', models.TextField(blank=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending Confirmation'), ('CONFIRMED', 'Confirmed'), ('COMPLETED', 'Completed'), ('CANCELLED_PATIENT', 'Cancelled by Patient'), ('CANCELLED_DOCTOR', 'Cancelled by Doctor'), ('NO_SHOW', 'No Show')], default='PENDING', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('doctor', models.ForeignKey(limit_choices_to={'doctor_profile__isnull': False}, on_delete=django.db.models.deletion.CASCADE, related_name='doctor_appointments', to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patient_appointments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['requested_date', 'requested_time'],
            },
        ),
    ]
