# Generated by Django 5.1.7 on 2025-04-20 14:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0001_initial'),
        ('users', '0003_remove_doctorprofile_availability_availabilityslot'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='availability_slot',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='appointment_booked', to='users.availabilityslot'),
        ),
    ]
