# Generated by Django 5.1.7 on 2025-04-22 18:51

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MedicineOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_details', models.TextField(help_text='List medications, dosage, frequency, duration, and any other instructions.')),
                ('notes', models.TextField(blank=True, help_text='Additional notes for the patient or pharmacy.', null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('doctor', models.ForeignKey(limit_choices_to={'doctor_profile__isnull': False}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='issued_medicine_orders', to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(limit_choices_to={'patient_profile__isnull': False}, on_delete=django.db.models.deletion.CASCADE, related_name='received_medicine_orders', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
